#!/usr/bin/env bash
# Syncs config/secrets.local.json into platform-specific secret files.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS="$ROOT/config/secrets.local.json"
ANDROID_PROPS="$ROOT/android/local.properties"
IOS_SECRETS="$ROOT/ios/Flutter/Secrets.xcconfig"
DART_DEFINES="$ROOT/config/dart_defines.json"

if [[ ! -f "$SECRETS" ]]; then
  echo "Missing $SECRETS"
  echo "Copy config/secrets.example.json to config/secrets.local.json and add your keys."
  exit 1
fi

python3 - "$SECRETS" "$ANDROID_PROPS" "$IOS_SECRETS" "$DART_DEFINES" <<'PY'
import json
import sys
from pathlib import Path

secrets_path = Path(sys.argv[1])
android_path = Path(sys.argv[2])
ios_path = Path(sys.argv[3])
dart_path = Path(sys.argv[4])

with secrets_path.open(encoding="utf-8") as f:
    secrets = json.load(f)

android_key = (secrets.get("GOOGLE_MAPS_ANDROID_KEY") or "").strip()
ios_key = (secrets.get("GOOGLE_MAPS_IOS_KEY") or "").strip()
geocoding_key = (secrets.get("GOOGLE_GEOCODING_KEY") or "").strip()

missing = [
    name
    for name, value in [
        ("GOOGLE_MAPS_ANDROID_KEY", android_key),
        ("GOOGLE_MAPS_IOS_KEY", ios_key),
        ("GOOGLE_GEOCODING_KEY", geocoding_key),
    ]
    if not value
]
if missing:
    raise SystemExit(f"Missing keys in {secrets_path}: {', '.join(missing)}")

lines: dict[str, str] = {}
if android_path.exists():
    for raw in android_path.read_text(encoding="utf-8").splitlines():
        if "=" in raw and not raw.strip().startswith("#"):
            k, v = raw.split("=", 1)
            lines[k.strip()] = v

lines["GOOGLE_MAPS_API_KEY"] = android_key
android_path.parent.mkdir(parents=True, exist_ok=True)
android_path.write_text(
    "\n".join(f"{k}={v}" for k, v in lines.items()) + "\n",
    encoding="utf-8",
)

ios_path.parent.mkdir(parents=True, exist_ok=True)
ios_path.write_text(
    "\n".join(
        [
            "// Generated by tool/bootstrap_secrets.sh — do not commit.",
            "// Edit config/secrets.local.json instead.",
            f"GOOGLE_MAPS_API_KEY={ios_key}",
            "",
        ]
    ),
    encoding="utf-8",
)

dart_path.parent.mkdir(parents=True, exist_ok=True)
dart_path.write_text(
    json.dumps({"GOOGLE_MAPS_API_KEY": geocoding_key}, indent=2) + "\n",
    encoding="utf-8",
)

print(f"Wrote {android_path}")
print(f"Wrote {ios_path}")
print(f"Wrote {dart_path}")
PY

echo "Done. Run: flutter run --dart-define-from-file=config/dart_defines.json"
